import { Octokit } from 'octokit'
import { config } from '../../config'

export const openTemplatePR = async ({
  octokit,
  repo,
  baseBranch,
  branchName,
}: {
  octokit: Octokit
  repo: string
  branchName: string
  baseBranch: string
}) => {
  const envConf = config()
  await octokit.rest.pulls.create({
    owner: envConf.github.org,
    repo,
    head: branchName,
    base: baseBranch,
    title: 'Template files from dev infra',
    body: 'This PR is auto generated by dev infra to copy over the template files to the new repo',
  })
}
