name: Sync the dev infrastructure (DRY RUN)
# Change this to on merge when done with the script
# as right now it is on push
on:
  workflow_run:
    workflows: ['test']
    types:
      - completed
    branches-ignore:
      - main

jobs:
  sync-infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      - run: npm run syncInfra
        env:
          DRY_RUN: true
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          GH_ORG_NAME: ${{ secrets.GH_ORG_NAME }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
