name: Sync the dev infrastructure
# Change this to on merge when done with the script
on: 'push'

jobs:
  sync-infra:
    # to build you need to test and install first, so we just need to build
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: npm run syncInfra
